# Generated by Django 5.2 on 2025-05-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
