# Generated by Django 5.2 on 2025-05-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='phone_number',
            field=models.CharField(default=1111, max_length=20),
            preserve_default=False,
        ),
    ]
