# Generated by Django 5.2 on 2025-05-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_master_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
    ]
