# Generated by Django 5.2 on 2025-11-29 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='master',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='master',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(max_length=1024)),
                ('icon', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='landing.master')),
            ],
            options={
                'ordering': ['sort_order'],
                'indexes': [models.Index(fields=['master'], name='landing_soc_master__1b670d_idx'), models.Index(fields=['href'], name='landing_soc_href_f65956_idx')],
            },
        ),
    ]
