# Generated by Django 5.2 on 2025-11-29 10:17

import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_remove_master_phone_number_master_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='color',
            field=models.CharField(blank=True, max_length=7, validators=[landing.models.validate_hex_color]),
        ),
    ]
