# Generated by Django 5.2 on 2025-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_alter_social_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
