# Generated by Django 5.2 on 2025-12-03 19:59

import django.db.models.deletion
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_alter_review_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='social',
            name='color',
            field=models.CharField(blank=True, choices=[('#1da1f2', 'Twitter'), ('#ed812b', 'Одноклассники'), ('#45668e', 'ВКонтакте'), ('#229ED9', 'Telegram'), ('#00ff00', 'Телефон')], max_length=7, validators=[landing.models.validate_hex_color]),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-brands fa-twitter', 'Twitter'), ('fa-brands fa-square-odnoklassniki', 'Одноклассники'), ('fa-brands fa-vk', 'ВКонтакте'), ('fa-brands fa-telegram', 'Telegram'), ('fa-solid fa-phone', 'Телефон')], max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название подраздела')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание подраздела')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='landing.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Подраздел услуги',
                'verbose_name_plural': 'Подразделы услуг',
                'ordering': ['service__name', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=255, verbose_name='Операция')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Примерное время (мин)')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='landing.service', verbose_name='Услуга (если без подраздела)')),
                ('subsection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='landing.servicesubsection', verbose_name='Подраздел услуги')),
            ],
            options={
                'verbose_name': 'Позиция прайса',
                'verbose_name_plural': 'Позиции прайса',
                'ordering': ['operation_name'],
            },
        ),
    ]
