# Generated by Django 5.2 on 2025-12-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_service_alter_social_color_alter_social_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='service_covers/', verbose_name='Обложка услуги'),
        ),
        migrations.AddField(
            model_name='servicesubsection',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='subsection_covers/', verbose_name='Обложка подраздела'),
        ),
    ]
