# Generated by Django 5.2 on 2025-12-09 11:38

import django.core.validators
import django.db.models.deletion
import landing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Изображение в галерее', 'verbose_name_plural': 'Изображения в галерее'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['sort_order'], 'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок изображения'),
        ),
        migrations.AlterField(
            model_name='master',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='master',
            name='specialty',
            field=models.CharField(blank=True, max_length=200, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='social',
            name='color',
            field=models.CharField(blank=True, choices=[('#1da1f2', 'Twitter'), ('#ed812b', 'Одноклассники'), ('#45668e', 'ВКонтакте'), ('#229ED9', 'Telegram'), ('#00ff00', 'Телефон')], max_length=7, validators=[landing.models.validate_hex_color], verbose_name='Цвет иконки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='href',
            field=models.CharField(max_length=1024, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, choices=[('fa-brands fa-twitter', 'Twitter'), ('fa-brands fa-square-odnoklassniki', 'Одноклассники'), ('fa-brands fa-vk', 'ВКонтакте'), ('fa-brands fa-telegram', 'Telegram'), ('fa-solid fa-phone', 'Телефон')], max_length=200, verbose_name='Класс иконки'),
        ),
        migrations.AlterField(
            model_name='social',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='landing.master', verbose_name='Мастер'),
        ),
    ]
